### ISSUE TITLE
Why can't I allow a site to read a file but not modify it?

### ISSUE THREAD

**Issue by kenchris** [WICG/writable-files#3]
subject says it all

**Comment by inexorabletash** [comment]
Do you mean: why can't the user presented with file selection UI specify what permissions they grant to the site for operations against that specific file? Or do you mean: why isn't there a way for site to request opening a file as read-only? Or ....?

For the latter: that's the API available today (via `<input type=file>`). For the former: does any UX on any platform work that way, i.e. pushing that decision on users up front?

(I think I'm missing the point of the question, so please clarify!)

**Comment by kenchris** [comment]
I think that the open dialog (which is platform UX) could make it clear whether the file will be read only or also allow write, or it might be able to have a visible checkbox like [Only allow reading], for people to opt out of the site actually modifying the file.

I think that sites would request either just read or read and write like ```open( { mode: "rw" } )``` then when the use choses a file (and potentially disallows write), it would resolve with a promise with what was accepted, like ```{ path: "filename", key: "yourgeneratedkey", mode: "rw" }```

Then the site can limit functionality or show an error if the accepted permission doesn't fulfill its requirements.

ie.

(rw should probably be an enum or such, or just have a ```{ allowModifications }``` or so)
```
  open( { mode: "rw" }).then(data => {
    if (data.mode == "r") {
      return showDialog("Your changes will not be stored locally, wish to store in the cloud?").then(...)...
    } 
  })
```

**Comment by kenchris** [comment]
Sorry for not being clear.

I do understand that there is an existing API (which has its own disadvantages UX/UI wise, especially on mobile[1]) but having this split up in two APIs which works differently is no real advantage, so I think that the new API should handle both cases.

This would also allow an app to read a file (say background image - and not modify) and re-read it on next visit without having to request it again (prompt user) or upload it to their server.

Now if you allowed it for reading directories etc, it could even work for a local photo viewer, which would ask before saving modifications or at least store them in new files.

[1] This is how people work around the default UI
```
<div style="width: 0px; height: 0px; overflow: hidden"><input type="file" id="inputfile"></input></div>
<div class="button" onclick="upload();">Upload file</div>
...
function upload(){
 document.getElementById('inputfile').click();
}
```

**Comment by drufball** [comment]
I think best practice is not to specify UI within a spec, since it can vary by browser. But I agree that there should be a `read` and a `readwrite` mode, which browsers could choose to treat differently in the UI. 

One way to do this is to have a single `open()` method, and then the browser returns the file in whatever mode it deems appropriate (perhaps with the "allow writing to file?" checkbox you mentioned).

The other way is to have two `open()` methods, one for `read` and one for `readwrite`. The browser could still give these different visual treaments, but it would allow the site to surface an error (i.e. "I need to be able to write this file and I can't") without doing the work to load the file.

Does one of those proposals solve your issue?
