### ISSUE TITLE
Serializable form of FileReference (as URL?)

### ISSUE THREAD

**Issue by thomaswilburn** [WICG/writable-files#7]
As the author of Caret, which is an editor for Chrome OS, I'm really interested in proposals like this that offer a way I could run my app in a browser, instead of relying on Chrome APIs that are probably not long for this world. I suspect that something like Caret might be a good thought experiment for finding places where the existing file APIs are insufficient to write serious in-browser applications.

One of the things that the existing Chrome app API allows is to serialize a file into a string ID, which can be later used to restore that file even after the app has been closed and re-opened. In Caret, we use this to persist tabs across app restarts: users can close the window, then re-open it later and find all their files still waiting to be edited. However, that doesn't appear possible with the API as it is now. Would it be possible to do something similar to what `URL.createObjectURL()` does, but obviously more persistent, and tied to a `File.restore()` method for turning it back into a FileReference?

**Comment by inexorabletash** [comment]
I'm a fan! The scenarios we've kicked about are retaining access during a page reload and building a "recently used" menu.

Aside: We'll want to merge the concept of "FileReference" with `FileEntry` (soon to be renamed `FileSystemEntry`) from https://github.com/WICG/entries-api - a previously Chrome-only type that's now being implemented in Edge and Firefox as well. Since that's becoming a _de facto_ standard, we should base types in this proposal on that work rather than suggesting redundant types.

I thought I had a bug suggesting that the Entry types should be clonable/serializable but not finding it now...

**Comment by mgiuca** [comment]
It might be useful for FileReferences to be serializable so they can be received by a [Web Share Target](https://wicg.github.io/web-share-target/). (Though maybe it's premature to suppose we'd implement file associations via Web Share Target.)

**Comment by mkruisselbrink** [comment]
I think having `blob:` and `filesystem:` URLs was a mistake I don't want to repeat for this API, but I do agree that we do want to support serializing these references to IDB/postMessage etc.
